/**
 * Seeded supplier master data — README §8.1.
 *
 * Transcribed verbatim from the approved prototype
 * (`design-handoff/ODM Supplier Visit.dc.html`, the `SUPPLIERS` array): 12 records
 * from the customer's Excel data sheets plus HEBEI HUATONG and TESK, which have
 * open reports. The screens were sized against exactly this data.
 *
 * The prototype writes "—" where the supplier did not supply a value; here that is
 * stored as `null` and the UI renders the em dash (or a field-specific fallback such
 * as "None recorded" for the track record).
 */

import type { Supplier } from "@/types/domain";

export const SUPPLIERS: readonly Supplier[] = [
  {
    id: "huatong",
    shortName: "HEBEI HUATONG",
    legalName: "Hebei Huatong Wires & Cables Group Co., Ltd.",
    establishedYear: "1993",
    companyCapital: null,
    employees: "6,000",
    factorySizeM2: "200,000 m²",
    certifications: "ISO9001, ISO14001, ISO45001, UL, CSA",
    productionCapacity: null,
    presidentName: null,
    websiteUrl: "htcablewire.com",
    country: "China",
    region: "Hebei",
    city: "Tangshan",
    address: "Luannan County, Tangshan, Hebei, China",
    tel: null,
    contactName: "Zoey Lin",
    contactTitle: "Overseas Sales Manager",
    contactWechat: "zoeylin_ht",
    contactEmail: "welcome@hebei-huatong.com",
    trackRecordEbara: "RHW-2 qualification in progress",
    productCategories: "RHW-2, SOOW, H07RN-F electrical cables",
    status: "under_qualification",
    dataSheetState: "partial",
    lastVisitDate: "Aug 12, 2026",
    reportCount: 1,
    internalNotes:
      "Group is listed and audited; financial risk considered low. Certification scope is the main gap for EU/JP constructions — only UL and CSA evidenced so far. Korea plant is the intended production site for EBARA orders to limit US tariff exposure; confirm plant-level UL listing before the first PO.",
    visitPhotoIds: ["f01", "f14", "f07"],
    contacts: [
      {
        id: "huatong-contact-1",
        name: "Zoey Lin",
        role: "Overseas Sales Manager",
        email: "welcome@hebei-huatong.com",
        phone: "",
        wechat: "zoeylin_ht",
      },
      {
        id: "huatong-contact-2",
        name: "Wang Tao",
        role: "Technical Director — Rubber Cables",
        email: "wangtao@hebei-huatong.com",
        phone: "+86 139 3155 4402",
        wechat: "wt_huatong",
      },
      {
        id: "huatong-contact-3",
        name: "Chen Li",
        role: "QA Manager",
        email: "qa@hebei-huatong.com",
        phone: "+86 186 3288 7710",
        wechat: "",
      },
    ],
  },
  {
    id: "tesk",
    shortName: "TESK",
    legalName: "Zhejiang Tesk Pump Industry Co., Ltd",
    establishedYear: null,
    companyCapital: null,
    employees: null,
    factorySizeM2: null,
    certifications: "ISO9001, CE",
    productionCapacity: null,
    presidentName: null,
    websiteUrl: null,
    country: "China",
    region: "Zhejiang",
    city: "Deqing",
    address: null,
    tel: null,
    contactName: null,
    contactTitle: null,
    contactWechat: null,
    contactEmail: null,
    trackRecordEbara: null,
    productCategories: "Stainless steel horizontal single-stage pumps",
    status: "under_qualification",
    dataSheetState: "pending",
    lastVisitDate: "Oct 08, 2026",
    reportCount: 1,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [],
  },
  {
    id: "wendy",
    shortName: "Wendy Pump",
    legalName: "Fujian Fuan Wendy Electrical Machinery Co., Ltd.",
    establishedYear: "1997",
    companyCapital: "CNY 2,300,000",
    employees: "120",
    factorySizeM2: "6,660 m²",
    certifications: "ISO9001",
    productionCapacity: "350,000",
    presidentName: "Guo Feng",
    websiteUrl: "www.wendypump.com",
    country: "China",
    region: "Fujian",
    city: "Fuan",
    address: "Qinxiyang Industrial Zone, Fuan, Fujian, China",
    tel: "+86-5936396061",
    contactName: "Frank",
    contactTitle: "Sales manager",
    contactWechat: "+86-13959364508",
    contactEmail: "frank@wendypump.com",
    trackRecordEbara: null,
    productCategories: "Electrical machinery, pumps",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "wendy-contact-1",
        name: "Frank",
        role: "Sales manager",
        email: "frank@wendypump.com",
        phone: "+86-5936396061",
        wechat: "+86-13959364508",
      },
    ],
  },
  {
    id: "hande",
    shortName: "HANDURO",
    legalName: "Zhejiang Hande Pump Industry Co., Ltd",
    establishedYear: "2014",
    companyCapital: "CNY 11,000,000",
    employees: "230",
    factorySizeM2: "18,500 m²",
    certifications: "ISO9001, ISO14001, CE",
    productionCapacity: "350,000",
    presidentName: "Peng Sheng",
    websiteUrl: "www.handuro.com",
    country: "China",
    region: "Zhejiang",
    city: "Wenling City",
    address: "No.218-8, Chenguang Road, East New District, Wenling City, Zhejiang, 317500, China",
    tel: "+86-57686329922",
    contactName: "Maggie",
    contactTitle: "Sales Manager",
    contactWechat: "+86-18958638700",
    contactEmail: "hande-maggie@handuro.com",
    trackRecordEbara: null,
    productCategories: "Pumps",
    status: "on_hold",
    dataSheetState: "received",
    lastVisitDate: "May 14, 2026",
    reportCount: 1,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "hande-contact-1",
        name: "Maggie",
        role: "Sales Manager",
        email: "hande-maggie@handuro.com",
        phone: "+86-57686329922",
        wechat: "+86-18958638700",
      },
    ],
  },
  {
    id: "amos",
    shortName: "AMOS",
    legalName: "Amos Fluid Technology Co., Ltd",
    establishedYear: "2004",
    companyCapital: "CNY 49,000,000",
    employees: "150",
    factorySizeM2: "23,276 m²",
    certifications: "ISO9001, ISO14001",
    productionCapacity: "3,000",
    presidentName: "Jake Mei",
    websiteUrl: "www.amospump.com",
    country: "China",
    region: "Anhui",
    city: "Ningguo",
    address: "No. 108 West Outside Ring Road, Ningguo, Anhui, China",
    tel: "+86-05634186739",
    contactName: "Luna Zou",
    contactTitle: "Sales manager",
    contactWechat: "zy657907087",
    contactEmail: "luna.zou@amospump.com",
    trackRecordEbara: null,
    productCategories: "Fluid technology, pumps",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "amos-contact-1",
        name: "Luna Zou",
        role: "Sales manager",
        email: "luna.zou@amospump.com",
        phone: "+86-05634186739",
        wechat: "zy657907087",
      },
    ],
  },
  {
    id: "dafu",
    shortName: "DAFU",
    legalName: "Dafu Intelligent Technology Co., Ltd.",
    establishedYear: "2022",
    companyCapital: "CNY 4,100,000",
    employees: "790",
    factorySizeM2: "24,600 m²",
    certifications: "ISO9001",
    productionCapacity: "3,465,000",
    presidentName: "Faming Lin",
    websiteUrl: "www.dafupump.com",
    country: "China",
    region: "Jiangxi",
    city: "Shangrao",
    address: "No.3 Gongfu Road, (Qurao) Demonstration High-Tech Zone, Shangrao, Jiangxi, China",
    tel: "+86-7932570776",
    contactName: "Bonita Chen",
    contactTitle: "Sales manager",
    contactWechat: "+86-15868660806",
    contactEmail: "trade05@dafupump.com",
    trackRecordEbara: null,
    productCategories: "Submersible pumps, submersible motors",
    status: "approved",
    dataSheetState: "received",
    lastVisitDate: "Jul 23, 2026",
    reportCount: 1,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "dafu-contact-1",
        name: "Bonita Chen",
        role: "Sales manager",
        email: "trade05@dafupump.com",
        phone: "+86-7932570776",
        wechat: "+86-15868660806",
      },
    ],
  },
  {
    id: "nanfang",
    shortName: "Nanfang / CNP",
    legalName: "Nanfang Pumps Co., Ltd.",
    establishedYear: "1991",
    companyCapital: "CNY 1,923,440,000",
    employees: "6,000",
    factorySizeM2: "500,000 m²",
    certifications: "ISO9001, ISO14001, ISO45001",
    productionCapacity: "1,000,000",
    presidentName: "Hang Jun",
    websiteUrl: "www.cnppump.com",
    country: "China",
    region: "Zhejiang",
    city: "Hangzhou",
    address: "No.2 Hengyi Street, Linping Econ. & Tech. Development Zone, Hangzhou, China",
    tel: "+86-571-88637351",
    contactName: "William",
    contactTitle: "Regional Manager",
    contactWechat: "William33221",
    contactEmail: "William@cnppump.com",
    trackRecordEbara: null,
    productCategories: "Pumps — full range",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "nanfang-contact-1",
        name: "William",
        role: "Regional Manager",
        email: "William@cnppump.com",
        phone: "+86-571-88637351",
        wechat: "William33221",
      },
    ],
  },
  {
    id: "bedford",
    shortName: "Bedford",
    legalName: "Guangzhou Bedford Electric Equipment Co., Ltd.",
    establishedYear: "2007",
    companyCapital: "CNY 30,000,000",
    employees: "152",
    factorySizeM2: "8,000 m²",
    certifications: "ISO9001, ISO14001, ISO45001, IPMS",
    productionCapacity: "350,000",
    presidentName: "Zhang Xuemei",
    websiteUrl: "www.bedford.com.cn",
    country: "China",
    region: "Guangdong",
    city: "Guangzhou",
    address: "Room 201/202, No.11 Yong'An Street, Chajiao, Liwan District, Guangzhou, China",
    tel: "+86-020-81891363",
    contactName: "Diana Shen",
    contactTitle: "Foreign Trade Manager",
    contactWechat: "+86-18688428738",
    contactEmail: "diana@bedford.com.cn",
    trackRecordEbara: null,
    productCategories: "Electric equipment",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "bedford-contact-1",
        name: "Diana Shen",
        role: "Foreign Trade Manager",
        email: "diana@bedford.com.cn",
        phone: "+86-020-81891363",
        wechat: "+86-18688428738",
      },
    ],
  },
  {
    id: "cnpnm",
    shortName: "CNP NM",
    legalName: "CNP NM Fire-fighting System Co., Ltd",
    establishedYear: "2013",
    companyCapital: "CNY 45,000,000",
    employees: "177",
    factorySizeM2: "100,000 m²",
    certifications: "ISO9001, ISO14001",
    productionCapacity: "3,000",
    presidentName: "Mr. Liu Weiping",
    websiteUrl: "www.nmfirepumps.com",
    country: "China",
    region: "Hunan",
    city: "Changsha",
    address: "No.45 Xi Chong Road, Quan Tang Street, Changsha City, Hunan Province, P.R. China",
    tel: "+86-73184091726",
    contactName: "Claire Liu",
    contactTitle: "Sales manager",
    contactWechat: "+86-14755045919",
    contactEmail: "claire@nmfirepump.com",
    trackRecordEbara: null,
    productCategories: "Fire-fighting pump systems",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "cnpnm-contact-1",
        name: "Claire Liu",
        role: "Sales manager",
        email: "claire@nmfirepump.com",
        phone: "+86-73184091726",
        wechat: "+86-14755045919",
      },
    ],
  },
  {
    id: "lingxiao",
    shortName: "Lingxiao",
    legalName: "Guangdong Lingxiao Pump",
    establishedYear: "1933",
    companyCapital: "CNY 350,000,000",
    employees: "814",
    factorySizeM2: "100,000 m²",
    certifications: "ISO9001, ISO14001, ISO45001",
    productionCapacity: "8,000,000",
    presidentName: "Haibo Wang",
    websiteUrl: "www.lingxiao.com.cn",
    country: "China",
    region: "Guangdong",
    city: "Yangchun",
    address: "117 Riverside Avenue, Spring Town, Yangchun City, Guangdong, China",
    tel: "+86-6627707236",
    contactName: "Amber",
    contactTitle: "Sales",
    contactWechat: "13829852608",
    contactEmail: "Amber@lingxiao.com.cn",
    trackRecordEbara: null,
    productCategories: "Multistage pumps, garden pumps",
    status: "approved",
    dataSheetState: "received",
    lastVisitDate: "Jun 18, 2026",
    reportCount: 1,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "lingxiao-contact-1",
        name: "Amber",
        role: "Sales",
        email: "Amber@lingxiao.com.cn",
        phone: "+86-6627707236",
        wechat: "13829852608",
      },
    ],
  },
  {
    id: "huanli",
    shortName: "Zhongke Huanli",
    legalName: "Zhongke Huanli Corp., Ltd.",
    establishedYear: "1992",
    companyCapital: "CNY 110,000,000",
    employees: "300",
    factorySizeM2: "56,000 m²",
    certifications: "ISO9001, CE, TUV, UL",
    productionCapacity: "20,000,000",
    presidentName: "Chen Jiani",
    websiteUrl: "www.china-hl.com",
    country: "China",
    region: "Zhejiang",
    city: "Wenling",
    address: "East Of Xincheng Avenue, Zeguo Town, Wenling City, Taizhou City, Zhejiang, China",
    tel: "+86-57686219699",
    contactName: "Lincy",
    contactTitle: "Sales Representative",
    contactWechat: "lincy1023",
    contactEmail: "hl@china-hl.com",
    trackRecordEbara: null,
    productCategories: "Pumps, motors",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "huanli-contact-1",
        name: "Lincy",
        role: "Sales Representative",
        email: "hl@china-hl.com",
        phone: "+86-57686219699",
        wechat: "lincy1023",
      },
    ],
  },
  {
    id: "yuanda",
    shortName: "Wenling Yuanda",
    legalName: "Wenling Yuanda Motor Co., Ltd",
    establishedYear: "1990",
    companyCapital: "CNY 10,000,000",
    employees: "50",
    factorySizeM2: "4,150 m²",
    certifications: "ISO9001, CE",
    productionCapacity: "120,000",
    presidentName: "Xueliang Yan",
    websiteUrl: "www.wlyddj.cn",
    country: "China",
    region: "Zhejiang Province",
    city: "Taizhou Wenling",
    address: "Nanquan Industrial Zone, Wenling, Zhejiang, China",
    tel: "+86-57686177707",
    contactName: "Katrina Yan",
    contactTitle: "Sales",
    contactWechat: "yylkatrina",
    contactEmail: "postmaster2@wlyddj.cn",
    trackRecordEbara: null,
    productCategories: "Electric motors",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "yuanda-contact-1",
        name: "Katrina Yan",
        role: "Sales",
        email: "postmaster2@wlyddj.cn",
        phone: "+86-57686177707",
        wechat: "yylkatrina",
      },
    ],
  },
  {
    id: "doyin",
    shortName: "Doyin",
    legalName: "Zhejiang Doyin Technology Co., Ltd",
    establishedYear: "1989",
    companyCapital: "CNY 300,000,000",
    employees: "2,500",
    factorySizeM2: "450,000 m²",
    certifications: "ISO9001",
    productionCapacity: "7,500,000",
    presidentName: "Fang Xiubao",
    websiteUrl: "www.doyin.com",
    country: "China",
    region: "Zhejiang",
    city: "Wenling",
    address: "No.19, South Of Songhang Road, Eastern New District, Wenling, Zhejiang, China",
    tel: "+86-576-86331298",
    contactName: "Wendy Zhao",
    contactTitle: "Sales Manager",
    contactWechat: "+86-13058767676",
    contactEmail: "doyin10@doyin.com",
    trackRecordEbara: null,
    productCategories: "Pumps, motors",
    status: "prospect",
    dataSheetState: "received",
    lastVisitDate: null,
    reportCount: 0,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "doyin-contact-1",
        name: "Wendy Zhao",
        role: "Sales Manager",
        email: "doyin10@doyin.com",
        phone: "+86-576-86331298",
        wechat: "+86-13058767676",
      },
    ],
  },
  {
    id: "shimge",
    shortName: "SHIMGE",
    legalName: "Shimge Pump Industry (Zhejiang) Co., Ltd",
    establishedYear: "1984",
    companyCapital: "CNY 3,800,000,000",
    employees: "3,500",
    factorySizeM2: "283,000 m²",
    certifications: "ISO9001, ISO14001, CE, CSA, RoHS, UL",
    productionCapacity: "15,000,000",
    presidentName: "Xu Longbo",
    websiteUrl: "www.shimgepump.com",
    country: "China",
    region: "Zhejiang",
    city: "Taizhou",
    address: "No.3 Bihai Street, Eastern New District, Wenling, Taizhou, Zhejiang, China",
    tel: "+86-576-86339960",
    contactName: "Lola Lu",
    contactTitle: "Sales manager",
    contactWechat: "Dolores-Lola",
    contactEmail: "lolalu@shimge.com",
    trackRecordEbara: null,
    productCategories: "Domestic pumps, booster sets",
    status: "approved",
    dataSheetState: "received",
    lastVisitDate: "Jul 21, 2026",
    reportCount: 1,
    internalNotes: null,
    visitPhotoIds: [],
    contacts: [
      {
        id: "shimge-contact-1",
        name: "Lola Lu",
        role: "Sales manager",
        email: "lolalu@shimge.com",
        phone: "+86-576-86339960",
        wechat: "Dolores-Lola",
      },
    ],
  },
];

export function getSupplier(id: string): Supplier | undefined {
  return SUPPLIERS.find((supplier) => supplier.id === id);
}

/**
 * The two letters shown in the `.blueprint` square on the suppliers list (30px)
 * and the supplier detail header (62px): the first two ASCII letters of the short
 * name, uppercased. "HEBEI HUATONG" → "HE", "TESK" → "TE", "Nanfang / CNP" → "NA".
 */
export function supplierInitials(supplier: Supplier): string {
  return supplier.shortName.replace(/[^A-Za-z]/g, "").slice(0, 2).toUpperCase();
}

/** Suppliers page subtitle — "14 records · 12 data sheets received". */
export const SUPPLIER_COUNT_LABEL = `${SUPPLIERS.length} records · ${
  SUPPLIERS.filter((supplier) => supplier.dataSheetState === "received").length
} data sheets received`;
